## CeresDB
FROM ubuntu:22.04

RUN useradd -m -s /bin/bash ceres

RUN apt update && \
    apt install --yes curl gdb iotop cron vim less net-tools && \
    apt clean \

RUN apt update && apt install --yes libssl-dev

ENV RUST_BACKTRACE 1

COPY ./ceresdb-server /usr/bin/ceresdb-server
RUN chmod +x /usr/bin/ceresdb-server

COPY ./docker/entrypoint-ci.sh /entrypoint.sh
COPY ./docs/minimal.toml /etc/ceresdb/ceresdb.toml

COPY ./docker/tini /tini
RUN chmod +x /tini

ARG USER ceres

ENTRYPOINT ["/tini", "--", "/entrypoint.sh"]
