{
 "title": "ceresdb",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "query": "ceresdbcluster" }
  ]
 },
 "panels": [
  {
   "title": "basic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "tps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(grpc_handler_duration_count{env=\"$env\", type=\"handle_write\"}[3m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "qps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_handler_duration_count{env=\"$env\", type = \"handle_query\"}[3m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th query/write duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_handler_duration_bucket{env=\"$env\"}[3m])) by (le, type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "query by table",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(table_read_request_counter{env=\"$env\"}[3m])) by (table) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th write duration details by instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_handler_duration_bucket{env=\"$env\", type=\"handle_write\"}[3m])) by (le, type, instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th query duration details by instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_handler_duration_bucket{env=\"$env\", type=\"handle_query\"}[3m])) by (le, type, instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th write partition table duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(partition_table_write_duration_bucket{env=\"$env\"}[3m])) by (le, type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rows by table",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(table_write_rows_counter{env=\"$env\"}[3m])) by (table) > 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(table_write_rows_counter{env=\"$env\"}[3m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "table rows by instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(table_write_rows_counter{env=\"$env\"}[3m])) by (instance) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total tables to write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(sum(rate(table_write_rows_counter{env=\"$env\"}[3m])) by (table))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "flush and stall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "flush count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(table_flush_duration_count{env=\"$env\"}[3m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th flush duration details by instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(table_flush_duration_bucket{env=\"$env\"}[3m])) by (le, instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th write stall duration details by instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(table_write_stall_duration_bucket{env=\"$env\"}[3m])) by (le, instance))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}